# Site settings
title: "Original Montana Film Guide"
description: "Original Montana Film Guide is a captivating series centered on movies filmed in 
Montana. Join hosts Josh Quick, Lauren Norby, and Daniel Mrgan, talented artists from Western Montana, 
as they explore, analyze, and occasionally praise these cinematic gems. The show delves into the 
essence of Montana’s influence on these films, questioning whether their unique qualities could have emerged 
elsewhere."
podcast-description: "Each Original Montana Film Guide is made in Missoula, Montana."
url:  "https://omfgpod.com" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Josh Quick"
  # email: "alessiofranceschi2@gmail.com"
  url: "quickjosh.com"
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll, Montana, Missoula, Movie, Josh Quick, Lauren Norby, Daniel Mrgan, Rancho Deluxe, Certain Women, 
the revenant, Damnation Alley, Illustrator, Cattle Queen of Montana]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: joshqu1ck
  card: summary
facebook:
  app_id: 
# logo: /assets/img/Podcast_Cover.png
social:
  name: Josh Quick
  links:
    - https://www.instagram.com/joshqu1ck/
    # - https://twitter.com/PandaSekh
    # - https://www.linkedin.com/in/alessio-franceschi/
lang: en

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Original Montana Film Guide
podcast_author: Josh Quick
# podcast_email: alessiofranceschi2@gmail.com
podcast_subtitle: "A Jekyll Theme designed for Podcasters"
podcast_summary: "A Jekyll Theme designed for Podcasters. This is your podcast's summary."
podcast_description: "A Jekyll Theme designed for Podcasters. This is your podcast's description."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: en
podcast_launch: "2019-07-20" #Launch date of your podcast
podcast_copyright: "Quick Media, LLC"
podcast_feed: 
# podcast_artwork: "/assets/img/Podcast_Cover.png"