analytics-id:
#Pages
pages:
  - { name: "Episodes", link: "episodes.html" }
  # - { name: "Patreon", link: "#" }
  - { name: "Shop", link: "https://www.quickfactsbooks.com/" }
  # - {name: 'GitHub', link: 'https://github.com/PandaSekh'}
  # - {name: 'Get This Theme', link: 'https://github.com/PandaSekh/Jekyll-Podcaster'}

social:
  - {
      icon: "instagram",
      type: "brand",
      link: "https://www.instagram.com/joshqu1ck/",
    }
  # - {icon: 'twitter', type: "brand", link: 'https://twitter.com/ArteLettura'}
  # - {icon: 'facebook', type: "brand", link: '#'}
  # - {icon: 'youtube', type: "brand", link: '#'}
  # - {icon: 'envelope', type: "solid", link: 'mailto:alessiofranceschi2@gmail.com'}
  - {
      icon: "rss",
      type: "solid",
      link: "https://anchor.fm/s/efdca448/podcast/rss",
    }

websites-podcast:
  - {
      name: "Apple Podcast",
      link: "https://podcasts.apple.com/us/podcast/original-montana-field-guide/id1724095733",
    }
  - {
      name: "Spotify",
      link: "https://open.spotify.com/show/0g4wKzJpLtuQ2VHR0RVLUZ",
    }

  - {
      name: "Google Podcast",
      link: "https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9lZmRjYTQ0OC9wb2RjYXN0L3Jzcw?sa=X&ved=0CAIQ9sEGahcKEwjQspHGkNGDAxUAAAAAHQAAAAAQAg",
    }

  - {
      name: "Amazon Podcasts",
      link: "https://www.iheart.com/podcast/269-original-montana-field-gui-140213131/",
    }
  - {
      name: "I Heart Radio",
      link: "https://www.iheart.com/podcast/269-original-montana-field-gui-140213131/",
    }

  - {
      name: "RSS",
      link: "https://open.spotify.com/show/0g4wKzJpLtuQ2VHR0RVLUZ",
    }

translate-date: true #See _includes/date.html to translate the months' name
shownotes: true

#Disqus
disqus:
  disqus_shortname:
